# # #

name: go-local

volumes:
  offermanagerdbdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  offermanagerdb:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37011:27017
    volumes:
      - offermanagerdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=offermanagerdbuser
      - MONGO_INITDB_ROOT_PASSWORD=offermanagerdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  synclocal:
    build: ./synclocal
    restart: no
    logging:
      options:
        max-size: '1m'
        max-file: '1'

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 9898:8080
