# # #

name: go

volumes:
  certbotdata:
  offermanagerdbdata:
  slamanagerdbdata:
  slamanagerbufferdbdata:
  slamanagerbridgedbdata:

secrets:
  pcgidbkey:
    file: PCGIDB.key

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: containrrr/watchtower
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 500mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: nginx:alpine-slim
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 500mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - certbotdata:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  certbot:
    image: certbot/certbot
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 500mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  offermanagerdb:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - offermanagerdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=offermanagerdbuser
      - MONGO_INITDB_ROOT_PASSWORD=offermanagerdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanagerdb:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 4gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - slamanagerdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=slamanagerdbuser
      - MONGO_INITDB_ROOT_PASSWORD=slamanagerdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanagerbufferdb:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 6gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - slamanagerbufferdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=slamanagerbufferdbuser
      - MONGO_INITDB_ROOT_PASSWORD=slamanagerbufferdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanagerbridgedb:
    image: postgres:alpine
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          memory: 4gb
    ports:
      - 37017:5432
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - slamanagerbridgedbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$SLAMANAGERBRIDGEDB_DB
      - POSTGRES_USER=$SLAMANAGERBRIDGEDB_USER
      - POSTGRES_PASSWORD=$SLAMANAGERBRIDGEDB_PASSWORD

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  backupd:
    image: ghcr.io/joao-vasconcelos/go-backupd:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 500mb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./backups/:/backups
    env_file:
      - .env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nextjs:
    image: ghcr.io/joao-vasconcelos/go-nextjs:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./storage/:/app/storage
    env_file:
      - .env
    secrets:
      - pcgidbkey

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanager-feeder:
    image: ghcr.io/joao-vasconcelos/go-slamanager-feeder:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./storage/:/app/storage
    env_file:
      - .env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanager-monitor:
    image: ghcr.io/joao-vasconcelos/go-slamanager-monitor:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 4gb
      mode: replicated
      replicas: 1
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - .env

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanager-buffer:
    image: ghcr.io/joao-vasconcelos/go-slamanager-buffer:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - .env
    secrets:
      - pcgidbkey

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanager-bridge:
    image: ghcr.io/joao-vasconcelos/go-slamanager-bridge:production
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 2gb
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    env_file:
      - .env