volumes:
  godbdata:
  tripsauditdbdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  godb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37011:27017
    volumes:
      - godbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=godbuser
      - MONGO_INITDB_ROOT_PASSWORD=godbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  tripsauditdb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37012:27017
    volumes:
      - tripsauditdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tripsauditdbuser
      - MONGO_INITDB_ROOT_PASSWORD=tripsauditdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  synclocal:
    build: ./synclocal
    restart: no
    logging:
      options:
        max-size: '1m'
        max-file: '1'
