# # #

name: go-local

volumes:
  offermanagerdbdata:
  slamanagerdbdata:
  slamanagerbufferdbdata:

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  offermanagerdb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37011:27017
    volumes:
      - offermanagerdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=offermanagerdbuser
      - MONGO_INITDB_ROOT_PASSWORD=offermanagerdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanagerdb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37012:27017
    volumes:
      - slamanagerdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=slamanagerdbuser
      - MONGO_INITDB_ROOT_PASSWORD=slamanagerdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanagerbufferdb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    ports:
      - 37013:27017
    volumes:
      - slamanagerbufferdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=slamanagerbufferdbuser
      - MONGO_INITDB_ROOT_PASSWORD=slamanagerbufferdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  synclocal:
    build: ./synclocal
    restart: no
    logging:
      options:
        max-size: '1m'
        max-file: '1'
