# # #

name: go

volumes:
  certbotdata:
  offermanagerdbdata:
  slamanagerdbdata:

secrets:
  pcgidbkey:
    file: PCGIDB.key

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  watchtower:
    image: containrrr/watchtower
    mem_limit: 2g
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nginx:
    image: nginx:alpine-slim
    restart: unless-stopped
    mem_limit: 2g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
      - certbotdata:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    mem_limit: 2g
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  offermanagerdb:
    image: mongo
    restart: unless-stopped
    mem_limit: 2g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - offermanagerdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=offermanagerdbuser
      - MONGO_INITDB_ROOT_PASSWORD=offermanagerdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanagerdb:
    image: mongo
    restart: unless-stopped
    mem_limit: 2g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - slamanagerdbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=slamanagerdbuser
      - MONGO_INITDB_ROOT_PASSWORD=slamanagerdbpassword

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  backupd:
    image: ghcr.io/joao-vasconcelos/go-backupd:production
    restart: unless-stopped
    mem_limit: 2g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./backups/:/backups
    env_file:
      - .env.production

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  nextjs:
    image: ghcr.io/joao-vasconcelos/go-nextjs:production
    restart: unless-stopped
    mem_limit: 2g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./storage/:/app/storage
    env_file:
      - .env.production
    secrets:
      - pcgidbkey

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanager-feeder:
    image: ghcr.io/joao-vasconcelos/go-slamanager-feeder:production
    restart: unless-stopped
    mem_limit: 2g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./storage/:/app/storage
    env_file:
      - .env.production
    secrets:
      - pcgidbkey

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  slamanager-monitor:
    image: ghcr.io/joao-vasconcelos/go-slamanager-monitor:production
    restart: unless-stopped
    mem_limit: 2g
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./storage/:/app/storage
    env_file:
      - .env.production
    secrets:
      - pcgidbkey