name: Build & Publish Docker Images

on:
  push:
    branches:
      - production

jobs:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-backupd:
    name: backupd (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image (backupd)
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./backupd
          file: ./backupd/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-backupd:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-nextjs:
    name: NextJS (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image (NextJS)
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./nextjs
          file: ./nextjs/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-nextjs:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-slamanager-feeder:
    name: SLA Manager - feeder (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image (SLA Manager - feeder)
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./slamanager-feeder
          file: ./slamanager-feeder/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-slamanager-feeder:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-slamanager-monitor:
    name: SLA Manager - monitor (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image (SLA Manager - monitor)
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./slamanager-monitor
          file: ./slamanager-monitor/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-slamanager-monitor:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-slamanager-buffer:
    name: SLA Manager - buffer (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image (SLA Manager - buffer)
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./slamanager-buffer
          file: ./slamanager-buffer/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-slamanager-buffer:${{ github.ref_name }}
