name: Build & Publish Docker Images

on:
  push:
    branches:
      - production

jobs:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-backupd:
    name: backupd (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set module key
        run: |
          echo "MODULE_KEY=backupd" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Calculate module SHA256 hash
        run: |
          find "./${{ env.MODULE_KEY }}" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1 > ${{ env.MODULE_KEY }}.hash
          echo "SHA256_HASH=$(cat ${{ env.MODULE_KEY }}.hash)" >> $GITHUB_ENV

      - name: Fetch hash cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.MODULE_KEY }}.hash
          key: ${{ github.ref_name }}-${{ env.MODULE_KEY }}-${{ env.SHA256_HASH }}

      - name: Login to GitHub Container Registry
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./${{ env.MODULE_KEY }}
          file: ./${{ env.MODULE_KEY }}/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-${{ env.MODULE_KEY }}:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-nextjs:
    name: NextJS (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set module key
        run: |
          echo "MODULE_KEY=nextjs" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Calculate module SHA256 hash
        run: |
          find "./${{ env.MODULE_KEY }}" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1 > ${{ env.MODULE_KEY }}.hash
          echo "SHA256_HASH=$(cat ${{ env.MODULE_KEY }}.hash)" >> $GITHUB_ENV

      - name: Fetch hash cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.MODULE_KEY }}.hash
          key: ${{ github.ref_name }}-${{ env.MODULE_KEY }}-${{ env.SHA256_HASH }}

      - name: Login to GitHub Container Registry
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./${{ env.MODULE_KEY }}
          file: ./${{ env.MODULE_KEY }}/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-${{ env.MODULE_KEY }}:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-slamanager-feeder:
    name: SLA Manager - feeder (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set module key
        run: |
          echo "MODULE_KEY=slamanager-feeder" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Calculate module SHA256 hash
        run: |
          find "./${{ env.MODULE_KEY }}" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1 > ${{ env.MODULE_KEY }}.hash
          echo "SHA256_HASH=$(cat ${{ env.MODULE_KEY }}.hash)" >> $GITHUB_ENV

      - name: Fetch hash cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.MODULE_KEY }}.hash
          key: ${{ github.ref_name }}-${{ env.MODULE_KEY }}-${{ env.SHA256_HASH }}

      - name: Login to GitHub Container Registry
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./${{ env.MODULE_KEY }}
          file: ./${{ env.MODULE_KEY }}/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-${{ env.MODULE_KEY }}:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-slamanager-monitor:
    name: SLA Manager - monitor (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set module key
        run: |
          echo "MODULE_KEY=slamanager-monitor" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Calculate module SHA256 hash
        run: |
          find "./${{ env.MODULE_KEY }}" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1 > ${{ env.MODULE_KEY }}.hash
          echo "SHA256_HASH=$(cat ${{ env.MODULE_KEY }}.hash)" >> $GITHUB_ENV

      - name: Fetch hash cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.MODULE_KEY }}.hash
          key: ${{ github.ref_name }}-${{ env.MODULE_KEY }}-${{ env.SHA256_HASH }}

      - name: Login to GitHub Container Registry
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./${{ env.MODULE_KEY }}
          file: ./${{ env.MODULE_KEY }}/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-${{ env.MODULE_KEY }}:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-slamanager-buffer:
    name: SLA Manager - buffer (Docker)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set module key
        run: |
          echo "MODULE_KEY=slamanager-buffer" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Calculate module SHA256 hash
        run: |
          find "./${{ env.MODULE_KEY }}" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1 > ${{ env.MODULE_KEY }}.hash
          echo "SHA256_HASH=$(cat ${{ env.MODULE_KEY }}.hash)" >> $GITHUB_ENV

      - name: Fetch hash cache
        uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.MODULE_KEY }}.hash
          key: ${{ github.ref_name }}-${{ env.MODULE_KEY }}-${{ env.SHA256_HASH }}

      - name: Login to GitHub Container Registry
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./${{ env.MODULE_KEY }}
          file: ./${{ env.MODULE_KEY }}/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-${{ env.MODULE_KEY }}:${{ github.ref_name }}
