name: Build & Publish Docker Images

on:
  push:
    branches:
      - production

jobs:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-dashboard:
    name: 'Build Docker Image (dashboard)'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image - dashboard
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./dashboard
          file: ./dashboard/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-dashboard:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  go-backupd:
    name: 'Build Docker Image (backupd)'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image - backupd
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./backupd
          file: ./backupd/Dockerfile
          tags: ghcr.io/joao-vasconcelos/go-backupd:${{ github.ref_name }}
